version: "3.8"

services:
  client-gen:
    image: openapitools/openapi-generator-cli
    command: >
      generate
      -i https://converter.swagger.io/api/convert?url=https://raw.githubusercontent.com/gdg-garage/dungeons-and-trolls/master/api/dungeonsandtrolls.swagger.json
      -g python-experimental
      -o /dungeons_and_trolls_generated_client
      --additional-properties=packageName=dungeons_and_trolls_client
    volumes:
      - "./dungeons_and_trolls_generated_client:/dungeons_and_trolls_generated_client"

  swagger-client-gen:
    image: swaggerapi/swagger-codegen-cli-v3
    ulimits:
      nofile: 122880
    command: >
      generate
      -i https://raw.githubusercontent.com/gdg-garage/dungeons-and-trolls/main/api/dungeonsandtrolls.swagger.json
      -l python
      -o /dungeons_and_trolls_generated_client
      -D packageName=dungeons_and_trolls_client
      -v
    volumes:
      - "./dungeons_and_trolls_generated_client:/dungeons_and_trolls_generated_client"
